"""Generate the research dashboards. Fully derived; never hand-edited."""
import csv
import glob
import json
import os
import sys
import time
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "benchmark"))

DASH = os.path.join(ROOT, "reports", "RESEARCH_DASHBOARD.md")
EXPD = os.path.join(ROOT, "reports", "EXPERIMENT_SUMMARY.md")


def main():
    from benchmark.stats import win_interval
    lines = ["# RESEARCH DASHBOARD", "",
             "Generated by `pipeline/dashboards.py`. Do not hand-edit.", "",
             f"_generated {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}_", "",
             "## Champion", ""]
    champ = os.path.join(ROOT, "postmortem_champion", "main.py")
    import hashlib
    csha = hashlib.sha256(open(champ, "rb").read()).hexdigest() if os.path.exists(champ) else "?"
    hedge = os.path.join(ROOT, "postmortem_hedge", "main.py")
    hsha = hashlib.sha256(open(hedge, "rb").read()).hexdigest() if os.path.exists(hedge) else "?"
    lines += ["| | name | sha256 |", "|---|---|---|",
              f"| PRIMARY | `ahmedberatozer-v51-lean-flock` | `{csha}` |",
              f"| HEDGE | `farm_2945_original` | `{hsha}` |", ""]

    slp = os.path.join(ROOT, "shadow_ladder", "ratings.json")
    if os.path.exists(slp):
        sl = json.load(open(slp, encoding="utf-8"))
        lines += ["## Shadow ladder", "",
                  f"- verdict: **{sl.get('verdict')}**",
                  f"- informative observations: **{sl.get('informative_observations')}** "
                  f"of {sl.get('total_observations')}",
                  f"- anchor: {sl.get('anchor', {}).get('agent')} = "
                  f"{sl.get('anchor', {}).get('value')} ({sl.get('anchor', {}).get('kind')})",
                  "- **no point ShadowRating is published**; see "
                  "`reports/SHADOW_LADDER_CALIBRATION.md`", ""]

    bp = os.path.join(ROOT, "simulation", "official", "backends.json")
    if os.path.exists(bp):
        reg = json.load(open(bp, encoding="utf-8"))
        lines += ["## Simulation", "",
                  "| backend | verified | note |", "|---|---|---|"]
        for b in reg.get("backends", []):
            lines.append(f"| {b.get('backend')} | {b.get('verified')} | "
                         f"{str(b.get('detail'))[:60]} |")
        lines += ["", "No public Rust engine was found; all experiments in this "
                  "phase ran on the official Python runtime. See "
                  "`reports/RUST_PARITY.md`.", ""]

    ep = os.path.join(ROOT, "shadow_ladder", "ladder_informativeness.json")
    if os.path.exists(ep):
        li = json.load(open(ep, encoding="utf-8"))
        lines += ["## Ladder calibration (88k real games)", "",
                  "| rating gap | games | P(higher rated wins) |", "|---|---|---|"]
        for b in li.get("gap_bins", [])[:8]:
            lines.append(f"| {b['gap_lo']:.0f}-{b['gap_hi']:.0f} | {b['games']:,} | "
                         f"{b['p']:.4f} |")
        e = li.get("elite_both_ge_2900", {})
        lines += ["", f"Elite only (both >= 2900): n={e.get('games', 0):,}  "
                  f"P={e.get('games') and round(e.get('wins', 0)/e['games'], 4)}", ""]

    # coverage
    try:
        from data_pipeline.lake import connect
        con = connect()
        n_ep = con.execute("SELECT count(*) FROM episodes").fetchone()[0]
        n_ag = con.execute("SELECT count(*) FROM agents").fetchone()[0]
        lin = con.execute("SELECT count(DISTINCT lineage_id) FROM agents "
                          "WHERE league_eligible").fetchone()[0]
        con.close()
        lines += ["## Data lake", "",
                  f"- episodes: **{n_ep:,}**",
                  f"- unique agent artifacts: **{n_ag}**",
                  f"- league-eligible lineages: **{lin}**", ""]
    except Exception as exc:  # noqa: BLE001
        lines += ["## Data lake", "", f"- unavailable: {exc}", ""]

    # latest matchup evidence
    mp = os.path.join(ROOT, "experiments", "final_meta_results.csv")
    if os.path.exists(mp):
        agg = defaultdict(lambda: [0, 0, 0, 0])
        for r in csv.DictReader(open(mp, encoding="utf-8")):
            if r.get("valid") != "1":
                continue
            a, b = r["candidate_name"], r["opponent_name"]
            k = tuple(sorted((a, b)))
            w, l = int(r["win"]), int(r["loss"])
            if a <= b:
                agg[k][0] += w; agg[k][1] += l
            else:
                agg[k][0] += l; agg[k][1] += w
            agg[k][2] += 1
        lines += ["## Top matchups (offline)", "",
                  "| A | B | A wins | n | Wilson 95% |", "|---|---|---|---|---|"]
        for (a, b), (w, l, _t, n) in sorted(agg.items(), key=lambda kv: -kv[1][3])[:8]:
            if n < 8:
                continue
            iv = win_interval(w, l, 0)
            lines.append(f"| {a} | {b} | {w}-{l} | {n} | "
                         f"[{iv['wilson_lo']:.3f}, {iv['wilson_hi']:.3f}] |")
        lines.append("")

    sp = os.path.join(ROOT, "simulation", "search", "results.json")
    if os.path.exists(sp):
        s = json.load(open(sp, encoding="utf-8"))
        sm = s.get("smoke", [])
        alive = [r for r in sm if r.get("verdict") == "keep"]
        alive.sort(key=lambda r: -r.get("win_rate", 0))
        lines += ["## Latest automated search", "",
                  f"- stacks evaluated: **{len(sm)}**",
                  f"- alive: **{len(alive)}**", "",
                  "| win rate | n | margin | genes on |", "|---|---|---|---|"]
        for r in alive[:5]:
            on = [k for k, v in r["flags"].items() if v]
            lines.append(f"| {r.get('win_rate', 0):.4f} | {r.get('games')} | "
                         f"${r.get('margin')} | {', '.join(on) or 'none'} |")
        lines.append("")

    lines += ["## Promotion decision", "",
              "**Champion unchanged.** No candidate cleared the promotion gate: "
              "no challenger improved on the reference against BOTH top agents, "
              "and the calibrated-rating leg of the 3075 gate cannot be "
              "satisfied with the current calibration. See "
              "`reports/3075_RESEARCH_CONCLUSION.md`.", ""]

    with open(DASH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    # experiment summary
    e = ["# EXPERIMENT SUMMARY", "",
         "Generated by `pipeline/dashboards.py`. Top 20 most recent runs.", "",
         "| experiment | candidate | games | W-L-T | win% | verdict |",
         "|---|---|---|---|---|---|"]
    rows = []
    for f in sorted(glob.glob(os.path.join(ROOT, "experiments", "**", "*.csv"),
                               recursive=True), key=os.path.getmtime,
                    reverse=True):
        rs = list(csv.DictReader(open(f, encoding="utf-8")))
        if not rs or "candidate_sha" not in rs[0]:
            continue
        v = [r for r in rs if r.get("valid") == "1"]
        if not v:
            continue
        W = sum(int(r["win"]) for r in v)
        L = sum(int(r["loss"]) for r in v)
        T = sum(int(r["tie"]) for r in v)
        rows.append((v[0]["candidate_name"], v[0]["opponent_name"], len(v),
                     W, L, T, os.path.basename(f)[:34]))
        if len(rows) >= 20:
            break
    for c, o, n, W, L, T, f in rows:
        iv = win_interval(W, L, T)
        verdict = "separated" if (iv["wilson_lo"] > 0.5 or iv["wilson_hi"] < 0.5) \
            else "not separated"
        e.append(f"| {f} | {c[:22]} vs {o[:18]} | {n} | {W}-{L}-{T} | "
                 f"{iv['win_rate']:.3f} | {verdict} |")
    with open(EXPD, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(e) + "\n")
    print(f"wrote {os.path.relpath(DASH, ROOT)}")
    print(f"wrote {os.path.relpath(EXPD, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
