"""Sealed real-seed splits.

The discipline that matters: the final pool is written and committed *before*
it is ever evaluated, and evaluated once. Everything else is bookkeeping in
service of that.
"""
import hashlib
import os


class SeedSplits:
    def __init__(self, directory, dev="REAL_dev.txt", holdout="REAL_holdout.txt",
                 final="REAL_final.txt"):
        self.dir = directory
        self.paths = {"dev": os.path.join(directory, dev),
                      "holdout": os.path.join(directory, holdout),
                      "final": os.path.join(directory, final)}

    def load(self, pool):
        p = self.paths[pool]
        with open(p, encoding="utf-8") as fh:
            seeds = [int(x.strip()) for x in fh if x.strip().isdigit()]
        if not seeds:
            raise ValueError(f"{p} contains no seeds")
        return seeds

    def digest(self, pool):
        return hashlib.sha256(open(self.paths[pool], "rb").read()).hexdigest()

    def problems(self):
        p = []
        pools = {}
        for name in self.paths:
            if not os.path.exists(self.paths[name]):
                p.append(f"missing split file {self.paths[name]}")
                continue
            s = self.load(name)
            pools[name] = s
            if len(s) != len(set(s)):
                dupes = [x for x in set(s) if s.count(x) > 1]
                p.append(f"{name}: duplicate seeds {dupes[:5]}")
        if len(pools) == 3:
            names = list(pools)
            for i in range(len(names)):
                for j in range(i + 1, len(names)):
                    a, b = names[i], names[j]
                    overlap = set(pools[a]) & set(pools[b])
                    if overlap:
                        p.append(f"{a} and {b} overlap on {len(overlap)} "
                                 f"seed(s), e.g. {sorted(overlap)[:3]}")
        return p

    def verify(self):
        p = self.problems()
        for x in p:
            print(f"  FAIL  {x}")
        if not p:
            for name in self.paths:
                print(f"  {name:<8} n={len(self.load(name)):>3}  "
                      f"sha256={self.digest(name)[:16]}")
            print("  splits are disjoint and duplicate-free")
        return p

    def seal(self):
        """Return the manifest text to commit alongside the seed files."""
        lines = ["# Sealed evaluation splits", "",
                 "Generated by `simcomp.SeedSplits`. The FINAL pool below was",
                 "written and committed before any evaluation and is run exactly",
                 "once. Do not tune on it.", ""]
        for name in ("dev", "holdout", "final"):
            s = self.load(name)
            lines += [f"## {name}", f"- count: {len(s)}",
                      f"- sha256: `{self.digest(name)}`", ""]
        return "\n".join(lines) + "\n"
