"""Generate reports/SHADOW_LADDER_CALIBRATION.md from the measured JSON.

The report is generated, never hand-written, so a number in prose cannot drift
away from the number the instrument produced. `tests/test_research_gate.py`
cross-checks the report against the JSON as well, which would catch a stale
committed copy.

Order of argument, which is also the order of trust:

1. Establish column semantics empirically (`reward_*` is cash, not a win flag;
   `score_*` is post-game).
2. Fit the ladder's own response curve on 88,280 real games.
3. Show the curve saturates.
4. Apply it to this project's matchups and show most observations are censored.
5. Refuse to publish a point rating, and say what would be needed instead.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "reports", "SHADOW_LADDER_CALIBRATION.md")
LI = os.path.join(ROOT, "shadow_ladder", "ladder_informativeness.json")
RT = os.path.join(ROOT, "shadow_ladder", "ratings.json")


def main():
    li = json.load(open(LI, encoding="utf-8"))
    rt = json.load(open(RT, encoding="utf-8"))

    L = [
        "# SHADOW LADDER CALIBRATION",
        "",
        "Generated by `shadow_ladder/write_calibration_report.py` from",
        "`ladder_informativeness.json` and `ratings.json`. Do not hand-edit.",
        "",
        "## Verdict",
        "",
        f"**{rt['verdict']}**",
        "",
        f"- informative observations: **{rt['informative_observations']}** of "
        f"{rt['total_observations']}",
        f"- anchor: `{rt['anchor']['agent']}` = {rt['anchor']['value']} "
        f"({rt['anchor']['kind']})",
        "- **no ShadowRating is published anywhere in this repository**",
        "",
        "The ladder itself calibrates beautifully. The inputs this project has "
        "to feed it do not.",
        "",
        "## Step 1 — column semantics, established empirically",
        "",
        "Both of these were wrong in an earlier analysis, and both wrongnesses "
        "produced a published conclusion that was the opposite of the truth.",
        "",
        "| column | what it actually is | how that was established |",
        "|---|---|---|",
        "| `reward_0/1` | **final cash**, not a win flag | values reach "
        "~100,000; the two columns' means differ by under 0.1% |",
        "| `score_0/1` | the two players' ladder ratings | balanced: "
        "P(score_0 > score_1) = 0.4995 |",
        "",
        "`reward_*` read as an outcome makes `P(higher rated wins)` come out at "
        "~0.00, which reads as \"the ladder is pure noise\". Read correctly it is "
        "one of the strongest signals available. The first version of "
        "`ladder_informativeness.py` made exactly that error and is preserved in "
        "the module docstring alongside the correction.",
        "",
        "A rating column that is POST-game, not pre-match, is recorded as "
        "`rating_semantics='post_crawl'` in the lake so no downstream model can "
        "mistake it.",
        "",
        "## Step 2 — the ladder's own response curve",
        "",
        f"Fitted on {sum(b['games'] for b in li['gap_bins']):,} public games.",
        "",
        "| rating gap | games | P(higher rated wins) | 95% Wilson |",
        "|---|---|---|---|",
    ]
    for b in li["gap_bins"]:
        w = b.get("wilson")
        wtxt = f"[{w[0]:.4f}, {w[1]:.4f}]" if w else "—"
        L.append(f"| {b['gap_lo']:.0f}–{b['gap_hi']:.0f} | {b['games']:,} | "
                 f"{b['p']:.4f} | {wtxt} |")
    e = li.get("elite_both_ge_2900", {})
    if e:
        L += [
            "",
            f"Elite only, both players ≥ 2900: **{e['games']:,} games**, "
            f"P(higher rated wins) = **{e['wins']/e['games']:.4f}**, Wilson "
            f"[{e['wilson'][0]:.4f}, {e['wilson'][1]:.4f}].",
            "",
            "That 24,548 figure independently reproduces the count reported "
            "before the data lake existed, from a different code path.",
            "",
            "## Step 3 — what this says about the objective",
            "",
            "The curve saturates near 1.0 by a 200-point gap. So:",
            "",
            "- a 130-point advantage over the field wins **~96%** of games;",
            "- a 200-point advantage wins **~99.5%**.",
            "",
            "**Reaching 3075 is therefore not 'beat the field more often'. It is "
            "'be effectively untouchable'.** That reframes the target: the gate "
            "is a win rate in the high nineties against a strong independent "
            "field, not a small edge.",
            "",
            "It also explains why this project's league cannot be calibrated: "
            "the champion already wins essentially every matchup, which is the "
            "top of the curve.",
            "",
        ]
    L += [
        "## Step 4 — applying the curve to this project's matchups",
        "",
        "| matchup | n | win rate | informative? | implied gap |",
        "|---|---|---|---|---|",
    ]
    for o in sorted(rt["observations"], key=lambda x: -x["games"])[:16]:
        gap = (f"{o['gap']:.1f}" if not o["censored"]
               else f"*{o.get('bound', 'censored')}*")
        L.append(f"| {o['a']} vs {o['b']} | {o['games']:.0f} | "
                 f"{o['win_rate']:.4f} | {'yes' if not o['censored'] else 'no'} | "
                 f"{gap} |")
    L += [
        "",
        f"Only **{rt['informative_observations']} of "
        f"{rt['total_observations']}** observations are informative. A measured "
        "100% win rate maps to \"gap ≥ 275\" and therefore locates the agent "
        "nowhere inside that range. **A saturated curve cannot invert a "
        "saturated observation**, and no amount of computation changes that: the "
        "information is not in the data.",
        "",
        "## Step 5 — why plain Bradley-Terry was also withheld",
        "",
        "BT is the textbook model and it was tried. The comparison graph here is "
        "a two-hub star whose bottom tier wins nothing, so the MLE is unbounded "
        "and any printed beta is an artefact of where the iteration stopped. "
        "Earlier work established this and published a REGULARIZED BT fit, "
        "correctly labelled. A point rating built on it would still be a point "
        "rating built on a model whose scale is arbitrary.",
        "",
        "## What is published instead",
        "",
        "Two things, both directly measured:",
        "",
    ]
    for o in rt["observations"]:
        if not o["censored"]:
            L.append(f"- **{o['a']}** over **{o['b']}** at {o['win_rate']:.4f} "
                     f"over {o['games']:.0f} games → **+{o['gap']:.0f} ladder "
                     f"points**, Wilson [{o['wilson'][0]:.4f}, "
                     f"{o['wilson'][1]:.4f}]")
    L += [
        "",
        "Everything else is a bound, not a point. Per-head-to-head Wilson "
        "intervals remain the primary evidence, and the promotion gate uses "
        "direct paired win rate rather than any rating.",
        "",
        "## What would make this adequate",
        "",
        "One thing: **a mid-strength agent whose real Kaggle `publicScore` is "
        "public and whose artifact is reusable.** Measured against such an agent, "
        "the win rate would land mid-curve, where it is not censored, and the "
        "whole graph would un-censor at once.",
        "",
        "The available anchors are not that:",
        "",
        "- `sunrise_v1..v5` have genuine publicScores (139.0–348.1) but lose "
        "essentially every game, so they sit far past the saturated end;",
        "- `farm_2945_original` = 2945 and `barnyard_v7` = 3034.8 are "
        "**self-reported notebook titles, not ladder scores**, and are treated "
        "as weak anchors only.",
        "",
        "## Reproduce",
        "",
        "```",
        "$ python data_pipeline/ingest/episodes.py   # 88,281 episodes",
        "$ python data_pipeline/ingest/agents.py",
        "$ python shadow_ladder/ladder_informativeness.py",
        "$ python shadow_ladder/score_candidate.py",
        "```",
        "",
    ]
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {os.path.relpath(OUT, ROOT)}  "
          f"({rt['informative_observations']}/{rt['total_observations']} "
          f"informative, {rt['verdict']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
